controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    # BEGIN: add broadcaster for each tracker here
    # broadcaster name should be distinct
    tracker_1_pose_broadcaster:
      type: pose_broadcaster/PoseBroadcaster

    tracker_2_pose_broadcaster:
      type: pose_broadcaster/PoseBroadcaster
    # END: add broadcaster for each tracker here
  
# BEGIN: configure broadcaster for each tracker here
# pose_name should be the same as tracker name in URDF
# frame_id should be the same as base link in URDF
tracker_1_pose_broadcaster:
  ros__parameters:
    pose_name: "tracker_1"
    frame_id: "polaris_vega_base"

tracker_2_pose_broadcaster:
  ros__parameters:
    pose_name: "tracker_2"
    frame_id: "polaris_vega_base"
# END: configure broadcaster for each tracker here