# controller manager for the ros2_control stack
# - by the prefix "ndi/", we spawn the controller manager under namespace "ndi"
ndi/controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    # BEGIN: add broadcaster for each tracker here
    # - broadcaster name should be distinct
    # - we should not add the prefix "ndi/" here as we have already done this for the controller manager
    tracker_1_pose_broadcaster:
      type: pose_broadcaster/PoseBroadcaster

    tracker_2_pose_broadcaster:
      type: pose_broadcaster/PoseBroadcaster
    # END: add broadcaster for each tracker here
  
# BEGIN: configure broadcaster for each tracker here
# - pose_name should be the same as tracker name in URDF
# - frame_id should be the same as base link in URDF
# - by the prefix "ndi/", we spawn the controllers under namespace "ndi"
ndi/tracker_1_pose_broadcaster:
  ros__parameters:
    pose_name: "tracker_1"
    frame_id: "polaris_vega_base"

ndi/tracker_2_pose_broadcaster:
  ros__parameters:
    pose_name: "tracker_2"
    frame_id: "polaris_vega_base"
# END: configure broadcaster for each tracker here